springdoc:
  api-docs:
    path: /v3/api-docs # Default path for OpenAPI 3.0 spec.  Important!
  swagger-ui:
    path: /swagger-ui.html
    
spring:
  application:
    name: PaySwift
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include:
      stacktrace: never

api:
  PaySwift:
    security:
      token:
        secret: ${SECRET_TOKEN}


