springdoc:
  api-docs:
    path: /v3/api-docs # Default path for OpenAPI 3.0 spec.  Important!
  swagger-ui:
    path: /swagger-ui.html
    
spring:
  application:
    name: PaySwift
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include:
      stacktrace: never

api:
  PaySwift:
    security:
      token:
        secret: suaChaveSecretaAqui


